export type AgentOperationalStatus = "ativo" | "util" | "ocioso" | "revisao" | "sobreposto";
export type AgentExecutionMode = "direto" | "planejado" | "monitoramento";
export type AgentValidationLevel = "leve" | "padrao" | "forte";
export type AgentBlockerStatus = "livre" | "monitorar" | "bloqueado";

export interface AgentOperationalProfile {
  id: string;
  empresa: "MENSURA" | "MIA" | "PCS" | "CONSOLIDADO";
  funcao: string;
  papel: string;
  quandoAcionar: string[];
  saidaEsperada: string[];
  quandoEscalar: string[];
  quandoNaoUsar: string[];
  statusOperacional: AgentOperationalStatus;
  modoExecucao: AgentExecutionMode;
  validacaoPadrao: AgentValidationLevel;
  estadoBloqueio: AgentBlockerStatus;
  observacao?: string;
}

export const AGENT_OPERATIONAL_PROFILES: Record<string, AgentOperationalProfile> = {
  main: {
    id: "main",
    empresa: "CONSOLIDADO",
    funcao: "Coordenação",
    papel: "Triagem, coordenação central, consolidação executiva e operação por exceção.",
    quandoAcionar: ["entrada geral", "pedido transversal", "decisão multiagente", "síntese executiva"],
    saidaEsperada: ["direcionamento", "síntese", "recomendação", "roteamento"],
    quandoEscalar: ["decisão estratégica", "ação externa sensível", "risco relevante"],
    quandoNaoUsar: ["análise especializada já claramente delegável"],
    statusOperacional: "ativo",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "livre",
    observacao: "Camada central de coordenação da Flávia.",
  },
  mensura: {
    id: "mensura",
    empresa: "MENSURA",
    funcao: "Operação técnica",
    papel: "Gestão técnica e executiva de obra, prazo, medição e desvios.",
    quandoAcionar: ["cronograma", "atraso", "medição", "SPI/CPI/EVM", "rotina de obra"],
    saidaEsperada: ["diagnóstico", "risco de prazo", "causa raiz", "ação recomendada"],
    quandoEscalar: ["atraso crítico", "impacto contratual", "conflito de prioridade de obra"],
    quandoNaoUsar: ["jurídico puro", "financeiro consolidado"],
    statusOperacional: "ativo",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "livre",
  },
  mia: {
    id: "mia",
    empresa: "MIA",
    funcao: "Operação premium",
    papel: "Relação executiva e qualidade percebida em obras de alto padrão.",
    quandoAcionar: ["relatório para cliente", "qualidade percebida", "desalinhamento fino", "comunicação sensível"],
    saidaEsperada: ["leitura objetiva", "mensagem refinada", "posicionamento recomendado"],
    quandoEscalar: ["cliente sensível em risco", "dano de confiança"],
    quandoNaoUsar: ["licitação", "edital", "orçamento puro"],
    statusOperacional: "ativo",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "livre",
  },
  pcs: {
    id: "pcs",
    empresa: "PCS",
    funcao: "Licitações e institucional",
    papel: "Edital, prazo, contrato público, restauro e exigência institucional.",
    quandoAcionar: ["edital", "prazo de licitação", "IPHAN", "contrato público", "impugnação"],
    saidaEsperada: ["risco", "conformidade", "prazo crítico", "ação recomendada"],
    quandoEscalar: ["perda de prazo", "risco contratual relevante"],
    quandoNaoUsar: ["obra corrente sem tema público", "marketing", "RH"],
    statusOperacional: "ativo",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "livre",
  },
  finance: {
    id: "finance",
    empresa: "CONSOLIDADO",
    funcao: "Financeiro",
    papel: "Visão consolidada de caixa, priorização financeira e pressão de vencimentos.",
    quandoAcionar: ["fluxo de caixa", "pagamentos", "recebimentos", "orçado vs realizado"],
    saidaEsperada: ["impacto", "priorização", "alerta financeiro", "recomendação executiva"],
    quandoEscalar: ["risco de caixa", "vencimento relevante", "conflito entre pagamentos críticos"],
    quandoNaoUsar: ["jurídico puro", "cronograma sem impacto financeiro"],
    statusOperacional: "ativo",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "livre",
  },
  juridico: {
    id: "juridico",
    empresa: "CONSOLIDADO",
    funcao: "Jurídico",
    papel: "Risco jurídico, contratual e reputacional sensível.",
    quandoAcionar: ["contrato sensível", "cláusula crítica", "notificação", "distrato"],
    saidaEsperada: ["leitura de risco", "ponto crítico", "cuidado recomendado"],
    quandoEscalar: ["risco jurídico concreto", "risco reputacional relevante"],
    quandoNaoUsar: ["dúvida operacional simples", "tema técnico puro"],
    statusOperacional: "util",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "monitorar",
  },
  marketing: {
    id: "marketing",
    empresa: "CONSOLIDADO",
    funcao: "Marketing",
    papel: "Posicionamento, conteúdo e redes institucionais.",
    quandoAcionar: ["LinkedIn", "pauta", "narrativa institucional", "posicionamento por marca"],
    saidaEsperada: ["pauta", "mensagem", "fila de aprovação", "oportunidade de conteúdo"],
    quandoEscalar: ["publicação sensível", "reposicionamento relevante"],
    quandoNaoUsar: ["contrato", "licitação", "rotina técnica pura"],
    statusOperacional: "util",
    modoExecucao: "planejado",
    validacaoPadrao: "padrao",
    estadoBloqueio: "monitorar",
  },
  producao: {
    id: "producao",
    empresa: "CONSOLIDADO",
    funcao: "Produção",
    papel: "Fluidez operacional de entrega e gargalos de execução.",
    quandoAcionar: ["sobrecarga", "dependência cruzada", "atraso de execução"],
    saidaEsperada: ["leitura de gargalo", "reorganização", "tensão operacional"],
    quandoEscalar: ["travamento da produção", "sobrecarga crítica"],
    quandoNaoUsar: ["jurídico", "marketing", "decisão financeira isolada"],
    statusOperacional: "util",
    modoExecucao: "planejado",
    validacaoPadrao: "padrao",
    estadoBloqueio: "livre",
  },
  bi: {
    id: "bi",
    empresa: "CONSOLIDADO",
    funcao: "BI / Dados",
    papel: "Leitura analítica, indicadores, tendências e desvios.",
    quandoAcionar: ["indicador", "tendência", "comparação", "desvio"],
    saidaEsperada: ["leitura sintética", "indicador relevante", "insight acionável"],
    quandoEscalar: ["desvio relevante sem explicação", "indicador crítico piorando"],
    quandoNaoUsar: ["execução operacional simples"],
    statusOperacional: "util",
    modoExecucao: "direto",
    validacaoPadrao: "padrao",
    estadoBloqueio: "livre",
  },
  suprimentos: {
    id: "suprimentos",
    empresa: "CONSOLIDADO",
    funcao: "Suprimentos",
    papel: "Compras, fornecedores e risco de abastecimento.",
    quandoAcionar: ["compra", "fornecedor", "prazo de entrega", "atraso material"],
    saidaEsperada: ["risco de suprimento", "contingência", "recomendação de compra"],
    quandoEscalar: ["item crítico sem cobertura", "risco de parar obra"],
    quandoNaoUsar: ["jurídico puro", "financeiro consolidado sem compra"],
    statusOperacional: "util",
    modoExecucao: "planejado",
    validacaoPadrao: "padrao",
    estadoBloqueio: "livre",
  },
  rh: {
    id: "rh",
    empresa: "CONSOLIDADO",
    funcao: "RH",
    papel: "Capacidade, alocação e risco humano da operação.",
    quandoAcionar: ["sobrecarga de pessoa", "alocação", "necessidade de contratação"],
    saidaEsperada: ["leitura de capacidade", "risco de dependência", "redistribuição sugerida"],
    quandoEscalar: ["colapso de capacidade", "decisão de contratação"],
    quandoNaoUsar: ["pauta comercial", "tema técnico puro"],
    statusOperacional: "util",
    modoExecucao: "planejado",
    validacaoPadrao: "padrao",
    estadoBloqueio: "monitorar",
  },
  autopilot: {
    id: "autopilot",
    empresa: "CONSOLIDADO",
    funcao: "Monitoramento",
    papel: "Monitoramento contínuo, silêncio operacional e cadência automática.",
    quandoAcionar: ["rotina recorrente", "falta de atualização", "checagem de sinais"],
    saidaEsperada: ["alerta útil", "ausência relevante de sinal", "follow-up sugerido"],
    quandoEscalar: ["falha recorrente", "silêncio crítico", "rotina essencial quebrada"],
    quandoNaoUsar: ["análise estratégica profunda"],
    statusOperacional: "revisao",
    modoExecucao: "monitoramento",
    validacaoPadrao: "leve",
    estadoBloqueio: "monitorar",
    observacao: "Célula em revisão, útil como monitor, ainda não estabilizada como agente pleno.",
  },
  orcamentista: {
    id: "orcamentista",
    empresa: "CONSOLIDADO",
    funcao: "Custos",
    papel: "Orçamento, composição de custo e medição de serviços.",
    quandoAcionar: ["composição", "orçamento", "medição", "comparação de custo"],
    saidaEsperada: ["composição crítica", "inconsistência", "leitura de custo"],
    quandoEscalar: ["divergência material de custo", "medição sensível"],
    quandoNaoUsar: ["jurídico puro", "comunicação institucional"],
    statusOperacional: "util",
    modoExecucao: "planejado",
    validacaoPadrao: "forte",
    estadoBloqueio: "livre",
  },
};
